name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make binaries directory
      run: mkdir bin/converters
    - name: Build Wavify
      run: g++ ./src/converter.cpp -DWAVIFY -static -std=c++23 -o bin/converters/wavify.exe
    - name: Build mp3ify
      run: g++ ./src/converter.cpp -DMP3IFY -static -std=c++23 -o bin/converters/mp3ify.exe
    - name: Copy ffmpeg to Converters directory
      run: copy libs/ffmpeg.exe bin/converters/
    - name: Package binary for upload
      uses: actions/upload-artifact@v4
      with:
          name: converters-WIN
          path: bin/converters/
          
