name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make binaries directory
      run: mkdir bin/wavify
    - name: Build Wavify
      run: g++ ./src/converter.cpp -DWAVIFY -static -std=c++23 -o bin/wavify/wavify.exe
    - name: Copy ffmpeg to Wavify directory
      run: copy libs/ffmpeg.exe bin/wavify/
    - name: Package binary for upload
      uses: actions/upload-artifact@v4
      with:
          name: wavify-WIN
          path: bin/wavify/
          
